# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

from utilities import fibonacci_sequence


even_fibs = []
fibonacci_generator = fibonacci_sequence()


for fib in fibonacci_generator:
    if fib > 4000000:
        fibonacci_generator.close()
        break
    if fib % 2 == 0:
        print(fib)
        even_fibs.append(fib)

cumulative_even_fib_sum = sum(even_fibs)

print(cumulative_even_fib_sum)
