# Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and difference are pentagonal and
# D = |P(k) − P(j)| is minimised; what is the value of D?

from utilities import is_pentagonal, nth_pentagonal_number

minimal_difference = 0

for i in range(1, 10000):
    for j in range(i, 10000):
        first = nth_pentagonal_number(i)
        second = nth_pentagonal_number(j)
        if is_pentagonal(first + second) and is_pentagonal(second - first):
            print(first, second)
            if minimal_difference == 0:
                minimal_difference = second - first
            elif second - first < minimal_difference:
                minimal_difference = second - first

print("Minimal difference: {}".format(minimal_difference))
